apiVersion: v1
kind: Service
metadata:
  name: ai-interview-backend
  namespace: ai-interview
spec:
  selector:
    app: ai-interview-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
